SHELL := /bin/bash
.SHELLFLAGS := -euo pipefail -c

APP_ENV := apps/web/.env.local
SUPABASE := pnpm exec supabase

.DEFAULT_GOAL := help

.PHONY: help install dev up env write-env stop reset status check lint typecheck test build

help:
	@printf "Targets:\n"
	@printf "  make dev        Start Supabase local, write apps/web/.env.local, then run the web app\n"
	@printf "  make up         Start Supabase local and write apps/web/.env.local\n"
	@printf "  make env        Regenerate apps/web/.env.local from Supabase local status\n"
	@printf "  make status     Show Supabase local status\n"
	@printf "  make reset      Reset the local Supabase database with migrations/seeds\n"
	@printf "  make stop       Stop Supabase local\n"
	@printf "  make check      Run lint, typecheck, tests and build\n"

install:
	pnpm install

dev: up
	pnpm dev

up: install write-env

env: write-env

write-env:
	@$(SUPABASE) start >/dev/null
	@mkdir -p apps/web
	@status="$$($(SUPABASE) status -o env)"; \
	api_url="$$(printf '%s\n' "$$status" | sed -n 's/^API_URL="\([^"]*\)"$$/\1/p')"; \
	publishable_key="$$(printf '%s\n' "$$status" | sed -n 's/^PUBLISHABLE_KEY="\([^"]*\)"$$/\1/p')"; \
	anon_key="$$(printf '%s\n' "$$status" | sed -n 's/^ANON_KEY="\([^"]*\)"$$/\1/p')"; \
	service_role_key="$$(printf '%s\n' "$$status" | sed -n 's/^SERVICE_ROLE_KEY="\([^"]*\)"$$/\1/p')"; \
	studio_url="$$(printf '%s\n' "$$status" | sed -n 's/^STUDIO_URL="\([^"]*\)"$$/\1/p')"; \
	if [[ -z "$$api_url" || -z "$$publishable_key" || -z "$$anon_key" || -z "$$service_role_key" ]]; then \
		echo "Could not read local Supabase credentials from 'supabase status -o env'." >&2; \
		exit 1; \
	fi; \
	{ \
		echo "# Generated by 'make env'. Do not commit."; \
		echo "NEXT_PUBLIC_SUPABASE_URL=$$api_url"; \
		echo "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$$publishable_key"; \
		echo "SUPABASE_URL=$$api_url"; \
		echo "SUPABASE_SERVICE_ROLE_KEY=$$service_role_key"; \
		echo "SUPABASE_ANON_KEY=$$anon_key"; \
	} > "$(APP_ENV)"; \
	echo "Wrote $(APP_ENV)"; \
	echo "Supabase API: $$api_url"; \
	if [[ -n "$$studio_url" ]]; then echo "Supabase Studio: $$studio_url"; fi

stop:
	$(SUPABASE) stop

reset:
	@$(SUPABASE) start >/dev/null
	$(SUPABASE) db reset
	$(MAKE) env

status:
	$(SUPABASE) status

lint:
	pnpm lint

typecheck:
	pnpm typecheck

test:
	pnpm test

build:
	pnpm build

check: lint typecheck test build
