import { DatabaseSync } from "node:sqlite";
import { writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";

import { DomainError, err, ok, type CardNumber, type Result } from "@yugioh/shared";

import { ensureDatabase, toCardNumber } from "./fm-gamedata-database.ts";

/**
 * Pulls the original game's equip compatibility out of `equipinfo` and writes
 * it as a generated module inside `packages/shared`.
 *
 * Which monsters an equip card accepts is **not** derivable from `classe` or
 * from the attribute — the original game curates a list per equip. Checked
 * against all 621 monsters, only three of the 34 lists coincide with a filter:
 * 657 Megamorph and 668 Bright Castle (every monster) and 659 Winged Trumpeter
 * (exactly `Fairy`). Harpie Lady is a `Winged Beast` that accepts Book of
 * Secret Arts; Steel Shell reaches 16 "shelled" monsters spread across several
 * classes. So the table has to be extracted, not approximated
 * (`docs/spells/equip-buffs.md` §2).
 *
 * ## Why the output lands in `packages/shared`
 *
 * `sumEquipBonuses` runs in `packages/engine`, which may import nothing but
 * `@yugioh/shared`, and `apply(state, action)` is a two-parameter function
 * with nowhere to inject a provider. Same reasoning as ADR-S2 in
 * `docs/spells/README.md`, which put `SPELL_EFFECTS` there for the same
 * reason. `packages/data` would be the natural home and is not reachable.
 *
 * Usage:
 *   node scripts/extract-fm-equip-compatibility.ts
 */

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const REPO_ROOT = resolve(PACKAGE_ROOT, "..", "..");
const OUTPUT_FILE = join(
  REPO_ROOT,
  "packages",
  "shared",
  "src",
  "duel",
  "spell-effects",
  "equip-compatibility.ts",
);

/** The 34 equip cards the original game defines. A drift here is a broken extraction. */
const EXPECTED_EQUIP_COUNT = 34;

type EquipRow = Readonly<{ equipId: number; cardId: number }>;

function readEquipRows(
  database: DatabaseSync,
): Result<ReadonlyMap<CardNumber, CardNumber[]>, DomainError> {
  const rows = database
    .prepare("select EquipId as equipId, CardId as cardId from equipinfo order by EquipId, CardId")
    .all() as readonly Record<string, unknown>[];

  const compatibility = new Map<CardNumber, CardNumber[]>();
  for (const row of rows) {
    const { equipId, cardId } = row as unknown as EquipRow;
    const equip = toCardNumber(Number(equipId));
    const monster = toCardNumber(Number(cardId));
    const existing = compatibility.get(equip);
    if (existing === undefined) {
      compatibility.set(equip, [monster]);
    } else {
      existing.push(monster);
    }
  }

  if (compatibility.size !== EXPECTED_EQUIP_COUNT) {
    return err(
      new DomainError(
        "The source table does not hold the expected equip cards.",
        "unexpected_equip_count",
        {
          found: compatibility.size,
          expected: EXPECTED_EQUIP_COUNT,
        },
      ),
    );
  }
  return ok(compatibility);
}

/**
 * The generated module. Entries are stored as one comma-joined string per
 * equip rather than as an array of strings: the 4041 pairs cost ~16 KB that
 * way against ~24 KB as arrays, and this module ships in the browser bundle
 * because `shared` has no build step. It is expanded once, at module load,
 * into the `Set` the lookup actually reads.
 */
function renderModule(compatibility: ReadonlyMap<CardNumber, CardNumber[]>): string {
  const entries = [...compatibility.entries()].sort(([left], [right]) => left.localeCompare(right));
  const pairCount = entries.reduce((total, [, monsters]) => total + monsters.length, 0);
  const lines = entries.map(([equip, monsters]) => `  "${equip}": "${monsters.join(",")}",`);

  return `import type { CardNumber } from "../../card/types.ts";

/**
 * Which monsters each equip card accepts, keyed by the equip's \`numero\`.
 *
 * GENERATED by \`packages/data/scripts/extract-fm-equip-compatibility.ts\` from
 * the \`equipinfo\` table of \`sg4e/YGOFM-gamedata\`. Do not edit by hand;
 * re-run the script instead.
 *
 * ${String(entries.length)} equip cards, ${String(pairCount)} compatible pairs. The lists are the
 * original game's own curation and do not follow \`classe\` or the attribute —
 * Harpie Lady is a \`Winged Beast\` that accepts Book of Secret Arts
 * (\`docs/spells/equip-buffs.md\` §2).
 *
 * Stored comma-joined rather than as arrays: \`shared\` has no build step, so
 * this module ships to the browser, and the joined form costs ~8 KB less.
 */
const COMPATIBILITY_SOURCE: Readonly<Record<CardNumber, string>> = Object.freeze({
${lines.join("\n")}
});

/** Expanded once at module load; every lookup is then a \`Set\` membership test. */
const COMPATIBILITY: ReadonlyMap<CardNumber, ReadonlySet<CardNumber>> = new Map(
  Object.entries(COMPATIBILITY_SOURCE).map(([equip, monsters]) => [
    equip,
    new Set(monsters.split(",")),
  ]),
);

/**
 * Whether \`hostNumber\` is a legal host for \`equipNumber\` in the original game.
 *
 * False for a card that is not an equip at all, which is what makes this safe
 * to call for any pair. An incompatible host is **not** a refusal: attaching
 * the card is a legal play that spends the turn's hand play and contributes 0
 * (\`docs/spells/equip-buffs.md\` §3).
 */
export function isEquipCompatible(equipNumber: CardNumber, hostNumber: CardNumber): boolean {
  return COMPATIBILITY.get(equipNumber)?.has(hostNumber) ?? false;
}

const EMPTY_HOSTS: ReadonlySet<CardNumber> = new Set();

/** The hosts \`equipNumber\` accepts, or an empty set when it is not an equip. */
export function equipCompatibleHosts(equipNumber: CardNumber): ReadonlySet<CardNumber> {
  return COMPATIBILITY.get(equipNumber) ?? EMPTY_HOSTS;
}

/** Every equip card the table knows, for tests and tooling. */
export function equipCardNumbers(): readonly CardNumber[] {
  return [...COMPATIBILITY.keys()];
}
`;
}

export async function extractEquipCompatibility(): Promise<
  Result<Readonly<{ equips: number; pairs: number }>, DomainError>
> {
  const databasePath = await ensureDatabase();
  if (!databasePath.ok) {
    return databasePath;
  }

  const database = new DatabaseSync(databasePath.value, { readOnly: true });
  try {
    const compatibility = readEquipRows(database);
    if (!compatibility.ok) {
      return compatibility;
    }

    await writeFile(OUTPUT_FILE, renderModule(compatibility.value), "utf8");
    return ok({
      equips: compatibility.value.size,
      pairs: [...compatibility.value.values()].reduce((total, list) => total + list.length, 0),
    });
  } finally {
    database.close();
  }
}

async function main(): Promise<number> {
  const result = await extractEquipCompatibility();
  if (!result.ok) {
    console.error(`Extraction failed (${result.error.code}): ${result.error.message}`);
    console.error(JSON.stringify(result.error.details, null, 2));
    return 1;
  }

  console.log(
    `Extracted ${String(result.value.equips)} equip cards ` +
      `and ${String(result.value.pairs)} compatible pairs to ${OUTPUT_FILE}.`,
  );
  return 0;
}

const invokedPath = process.argv[1];
const isEntryPoint =
  invokedPath !== undefined && fileURLToPath(import.meta.url) === resolve(invokedPath);
if (isEntryPoint) {
  process.exitCode = await main();
}
