import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Card } from "@yugioh/shared";
import { UNPRICED_CARD_STARS } from "@yugioh/shared";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const escapeSql = (value: string) => value.replaceAll("'", "''");

export function generateCardPricesSeed(cards: readonly Card[], datasetVersion: string): string {
  const rows = cards.filter((card) => card.password !== null).map((card) =>
    `('${escapeSql(card.numero)}', '${card.password!.replaceAll(/\s/g, "")}', ${String(card.estrelas ?? UNPRICED_CARD_STARS)}, '${escapeSql(datasetVersion)}')`,
  );
  return `-- Generated by packages/data/scripts/generate-card-prices-seed.ts. Do not edit.\ninsert into public.card_prices (numero, password_digits, stars, dataset_version) values\n${rows.join(",\n")}\non conflict (numero) do update set password_digits = excluded.password_digits, stars = excluded.stars, dataset_version = excluded.dataset_version;\n`;
}

async function main() {
  const generated = resolve(packageRoot, "generated");
  const cards = JSON.parse(await readFile(resolve(generated, "cards.json"), "utf8")) as Card[];
  const seal = JSON.parse(await readFile(resolve(generated, "dataset-seal.json"), "utf8")) as { generatedAt: string };
  await writeFile(resolve(packageRoot, "../../supabase/migrations/0011_seed_card_prices.sql"), generateCardPricesSeed(cards, seal.generatedAt));
}
if (process.argv[1] === fileURLToPath(import.meta.url)) await main();
